public enum PerkType
{
    Speed = 0,
    RaySpeed = 1,
    RayPathLenght = 2,
    RayDelay = 3,
    RayDamageAreaRadius = 4,
    RayDamage = 5,

    EWaveFactor = 6,
    EBoss = 7,
    EChampion = 8,
    ESpeedAura = 9,
    ESpeedAuraEffect = 10,
    EAfterDeathExplosion = 11,
    PBarrels = 12,
    Ionization = 13,
    IonizationEffect = 14,
    EHunter = 15,
    EMother = 16,
    Amplifier = 17,
    FocusLens = 18,
    DivergingLens = 19,
    PowerController = 20,
    LensSystem = 21,
    MagneticManipulator = 22,
    ESlowAuraEffect = 23,
    ESlowAura = 24,
    PShift = 25,
    RayReverse = 26,
    EAgressor = 27,
    EnergyRegen = 28,
    EnergyAbsorber = 29,

    PlayerMaxHP = 30,
    PlayerLifeSupport = 31,
    PlayerDodge = 32,
    PlayerFireResist = 33,
    PlayerStunResist = 34,
    PlayerSlowdownResist = 35,
    PlayerElectricityResist = 36,
    PlayerRadiationResist = 37,

    MineralEffect = 38,
    RayError = 39,

    EnergyCapacity = 40,
    GravityMatter = 41,
    Xenomineral = 42,
    RayCostReduction = 43,
    FrostbiteEffect = 44,
    ColdAOE = 45,
}
