//autogenerated
public enum AddressKeys
{
   Mob_First,
   Fx_Dust,
   Fx_SpeedUp,
   Fx_Aura0,
   Mob_Second,
   Fx_Explosion,
   Snd_Explosion,
   Obj_Barrel,
   Mob_SpdBuff,
   Fx_Radiation,
   Mob_Child,
   Fx_AuraBoss,
   Ico_Laser,
   Ico_Battery,
   Ico_Ship,
   Ico_Amplifier,
   Ico_Box,
   Ico_Chip,
   Ico_Lens,
   Ico_Magnet,
   Ico_Radiation,
   Ico_Servo,
   Ico_SpeedBoost,
   Ico_DivergingLens,
   Ico_PowerController,
   Ico_Lenses,
}
public static class AddressKeysConverter
{
    public static string Convert(AddressKeys key)
    {
        switch (key)
        {
            case AddressKeys.Mob_First:
                return "Mob_First";
            case AddressKeys.Fx_Dust:
                return "Fx_Dust";
            case AddressKeys.Fx_SpeedUp:
                return "Fx_SpeedUp";
            case AddressKeys.Fx_Aura0:
                return "Fx_Aura0";
            case AddressKeys.Mob_Second:
                return "Mob_Second";
            case AddressKeys.Fx_Explosion:
                return "Fx_Explosion";
            case AddressKeys.Snd_Explosion:
                return "Snd_Explosion";
            case AddressKeys.Obj_Barrel:
                return "Obj_Barrel";
            case AddressKeys.Mob_SpdBuff:
                return "Mob_SpdBuff";
            case AddressKeys.Fx_Radiation:
                return "Fx_Radiation";
            case AddressKeys.Mob_Child:
                return "Mob_Child";
            case AddressKeys.Fx_AuraBoss:
                return "Fx_AuraBoss";
            case AddressKeys.Ico_Laser:
                return "Ico_Laser";
            case AddressKeys.Ico_Battery:
                return "Ico_Battery";
            case AddressKeys.Ico_Ship:
                return "Ico_Ship";
            case AddressKeys.Ico_Amplifier:
                return "Ico_Amplifier";
            case AddressKeys.Ico_Box:
                return "Ico_Box";
            case AddressKeys.Ico_Chip:
                return "Ico_Chip";
            case AddressKeys.Ico_Lens:
                return "Ico_Lens";
            case AddressKeys.Ico_Magnet:
                return "Ico_Magnet";
            case AddressKeys.Ico_Radiation:
                return "Ico_Radiation";
            case AddressKeys.Ico_Servo:
                return "Ico_Servo";
            case AddressKeys.Ico_SpeedBoost:
                return "Ico_SpeedBoost";
            case AddressKeys.Ico_DivergingLens:
                return "Ico_DivergingLens";
            case AddressKeys.Ico_PowerController:
                return "Ico_PowerController";
            case AddressKeys.Ico_Lenses:
                return "Ico_Lenses";
                default: return "";
        }
    }
}