//autogenerated
public enum AddressKeys
{
   Mob_First,
   Fx_Dust,
   Fx_SpeedUp,
   Fx_Aura0,
   Mob_second,
   Fx_Explosion,
   Snd_Explosion,
   Obj_Barrel,
}
public static class AddressKeysConverter
{
    public static string Convert(AddressKeys key)
    {
        switch (key)
        {
            case AddressKeys.Mob_First:
                return "Mob_First";
            case AddressKeys.Fx_Dust:
                return "Fx_Dust";
            case AddressKeys.Fx_SpeedUp:
                return "Fx_SpeedUp";
            case AddressKeys.Fx_Aura0:
                return "Fx_Aura0";
            case AddressKeys.Mob_second:
                return "Mob_second";
            case AddressKeys.Fx_Explosion:
                return "Fx_Explosion";
            case AddressKeys.Snd_Explosion:
                return "Snd_Explosion";
            case AddressKeys.Obj_Barrel:
                return "Obj_Barrel";
                default: return "";
        }
    }
}