//autogenerated
public static class Addresses
{
   public static string Fx_Dust = "Fx_Dust";
   public static string Fx_SpeedUp = "Fx_SpeedUp";
   public static string Fx_Aura0 = "Fx_Aura0";
   public static string Mob_Second = "Mob_Second";
   public static string Fx_Explosion = "Fx_Explosion";
   public static string Snd_Explosion = "Snd_Explosion";
   public static string Obj_Barrel = "Obj_Barrel";
   public static string Mob_SpdBuff = "Mob_SpdBuff";
   public static string Fx_Radiation = "Fx_Radiation";
   public static string Mob_Child = "Mob_Child";
   public static string Fx_AuraBoss = "Fx_AuraBoss";
   public static string Ico_Laser = "Ico_Laser";
   public static string Ico_Battery = "Ico_Battery";
   public static string Ico_Ship = "Ico_Ship";
   public static string Ico_Amplifier = "Ico_Amplifier";
   public static string Ico_Box = "Ico_Box";
   public static string Ico_Chip = "Ico_Chip";
   public static string Ico_Lens = "Ico_Lens";
   public static string Ico_Magnet = "Ico_Magnet";
   public static string Ico_Radiation = "Ico_Radiation";
   public static string Ico_Servo = "Ico_Servo";
   public static string Ico_SpeedBoost = "Ico_SpeedBoost";
   public static string Ico_DivergingLens = "Ico_DivergingLens";
   public static string Ico_PowerController = "Ico_PowerController";
   public static string Ico_Lenses = "Ico_Lenses";
   public static string Ico_SpeedServo = "Ico_SpeedServo";
   public static string Char_standart = "Char_standart";
   public static string Mob_Artillery = "Mob_Artillery";
   public static string Obj_Heart = "Obj_Heart";
   public static string Mob_Slowdowner = "Mob_Slowdowner";
   public static string Mob_First = "Mob_First";
   public static string Ico_ShiftSystem = "Ico_ShiftSystem";
   public static string Ico_Reverse = "Ico_Reverse";
   public static string Mob_Heavy = "Mob_Heavy";
   public static string Mob_Fortress = "Mob_Fortress";
   public static string Main_en = "Main_en";
   public static string Main_ru = "Main_ru";
}
