//autogenerated
public enum LocKeys
{
    //Играть
    Play,
    //Нет
    None,
    //Скорость
    Speed,
}
public static class LocKeyConverter
{
    public static string Convert(LocKeys key)
    {
        switch (key)
        {
            case LocKeys.Play:
                return "Play";
            case LocKeys.None:
                return "None";
            case LocKeys.Speed:
                return "Speed";
                default: return "";
        }
    }
}