//autogenerated
public enum LocKeys
{
    //Играть
    Play,
}
public static class LocKeyConverter
{
    public static string Convert(LocKeys key)
    {
        switch (key)
        {
            case LocKeys.Play:
                return "Play";
                default: return "";
        }
    }
}